name: Build Foundry Module
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.2
    - name: Install PNPM
      uses: pnpm/action-setup@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.2.0
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Run build
      run: pnpm run bundle
    - name: Upload bundle
      id: bundle-upload-step
      uses: actions/upload-artifact@v4.6.1
      with:
        name: garrison.zip
        path: dist/
    - name: Generate install JSON
      uses: maxgfr/github-change-json@main
      with:
        path: dist/module.json
        key: download
        value: ${{ steps.bundle-upload-step.outputs.artifact-url }}
    - name: Update release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        files: dist/module.json
        release: unstable
        message: Latest unstable build
        prerelease: true